name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - name:                 Cancel Previous Runs
        uses:                 styfle/cancel-workflow-action@9f10b1b9fa56e99e4c5d12c2a085c8a0c37ab0ac # 0.10.1
      - name: Hello
        run: |
          - echo "Hello"